# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Command to build the project
cmd = "pnpm build && go run github.com/a-h/templ/cmd/templ generate && go build -o tmp/main ./cmd/"

delay = 1000

# Binary to run after build
bin = "./tmp/main"

# Working directory
full_bin = "./tmp/main"

# Watch these directories for changes
include_ext = ["go", "tpl", "tmpl", "templ", "html", "ts"]

exclude_regex = [".*_templ.go"]

# Ignore these files/directories
exclude_dir = ["vendor", "assets/js", "node_modules"]

# Print build log on terminal
log = "debug"
