name: Send Daily Tides

on:
  schedule:
    # Winter time (UTC+1): 9:30 AM Canary = 8:30 AM UTC
    # Runs from last Sunday of October to last Sunday of March
    - cron: '30 8 * 1-3,11-12 *'
    - cron: '30 8 1-24 10 *'  # Early October before DST ends
    - cron: '30 8 25-31 3 *'  # Late March after DST starts
    
    # Summer time (UTC+2): 9:30 AM Canary = 7:30 AM UTC  
    # Runs from last Sunday of March to last Sunday of October
    - cron: '30 7 * 4-9 *'    # April through September
    - cron: '30 7 1-24 3 *'   # Early March before DST
    - cron: '30 7 25-31 10 *' # Late October after DST ends
    
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  send-daily-tides:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Daily Tide Reports
        run: |
          curl -X POST "${{ secrets.APP_URL }}/jobs/send-tide-extremes" \
            -H "X-API-Key: ${{ secrets.API_KEY }}" \
            -H "Content-Type: application/json" \
            --fail-with-body \
            --max-time 60
        env:
          APP_URL: ${{ secrets.APP_URL }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Notify on failure
        if: failure()
        run: |
          echo "Daily tide job failed! Check the logs and app status."
          # You could add Slack/Discord notification here if needed