name: Send Daily Tides

on:
  schedule:
    # Canary 9:30 AM in UTC time

    # ⛄ Winter: UTC+0
    - cron: '30 9 * 1-3,11-12 *'     # Jan–Mar, Nov–Dec
    - cron: '30 9 * 10 *'            # Entire October (DST ends late October)
    - cron: '30 9 * 3 *'             # Entire March (DST starts late March)

    # ☀️ Summer: UTC+1 → run at 8:30 UTC
    - cron: '30 8 * 4-9 *'           # April–September only
    
  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  send-daily-tides:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send Daily Tide Reports
        run: |
          curl -X POST "${{ secrets.APP_URL }}/jobs/send-tide-extremes" \
            -H "X-API-Key: ${{ secrets.API_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
            -H "Content-Type: application/json" \
            --fail-with-body \
            --max-time 60

      - name: Notify on failure
        if: failure()
        run: |
          echo "Daily tide job failed! Check the logs and app status."
